sudo: required

env:
  global:
    - DOCKER_IMAGE="spark-jobserver:ci"
    - DOCKER_API_VERSION="1.24"

language: go
go:
  - 1.7

services:
  - docker

cache:
  directories:
    - docker

before_install:
  - go get github.com/tonistiigi/buildcache/cmd/buildcache

install:
  - if [ -e docker/latest_image.tar.gz ]; then
      docker load -i docker/latest_image.tar.gz;
    fi
  - if [ -e docker/latest_cache.tar.gz ]; then
      docker load -i docker/latest_cache.tar.gz;
    fi
  - echo "docker/" >> .dockerignore
  - docker build -f Dockerfile.test -t $DOCKER_IMAGE .
  - docker save $DOCKER_IMAGE | gzip > docker/latest_image.tar.gz
  - sudo `which buildcache` save -o docker/latest_cache.tar.gz $DOCKER_IMAGE
  - sudo chown $USER docker/latest_cache.tar.gz

script:
  - docker run `/bin/bash <(curl -s https://codecov.io/env)` --rm -t -i $DOCKER_IMAGE
